### ISSUE TITLE
replaceStream fails silently

### ISSUE THREAD

**Issue by exrhizo** [skyway/skyway-peer-authentication-samples#8]
## Environment
- SDK version `3.0.1`
- Device
- OS `Mac OS Catalina 10.15.5`
- Network `localhost`

## Steps to reproduce the problem

Setup a mesh room
Connect two peers with audio and video tracks
Have one peer call replaceStream() without an audio track

Nothing changes on the receiving side

## Expected behavior

I believe I need to have a peer leave and then rejoin the room with the different stream, if the video or audio are outside parameters.

## Other information

I think this is the:
InvalidModificationError
https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender/replaceTrack

**Comment by ibuibu** [comment]
I'm sorry for the delay in replying.

The action you wrote is a process that cannot be executed due to SDK specifications.

I've added a note to the URL of the document to that effect.

Thank you for your understanding.

https://webrtc.ecl.ntt.com/en/api-reference/javascript.html#replacestream-stream
